--v1.0
SELECT CASE
        WHEN MOVIES.BUDGET = (
            SELECT (MIN(MOVIES.BUDGET))::REAL
            FROM MOVIES
        ) THEN 'least expensive'
        ELSE 'most profitable'
    END AS FEATURE,
    MOVIES.TITLE
FROM MOVIES
WHERE (
        SELECT MAX(MOVIES.GROSS - MOVIES.BUDGET)
        FROM MOVIES
    ) = MOVIES.GROSS - MOVIES.BUDGET
    OR (
        SELECT MIN(MOVIES.BUDGET)
        FROM MOVIES
    ) = MOVIES.BUDGET
ORDER BY 1,
    2 ASC;