--v1.1

SELECT DISTINCT DIRECTORS.DIRECTOR,
	COALESCE(MIN(MOVIES.GROSS - MOVIES.BUDGET), -1) AS MINPROFIT,
	COALESCE(MAX(MOVIES.GROSS - MOVIES.BUDGET), -1) AS MAXPROFIT,
	TRUNC(COALESCE(AVG(MOVIES.GROSS), -1), 2) AS AVERAGEPROFIT
FROM DIRECTORS
	LEFT JOIN MOVIES ON DIRECTORS.DIRECTOR = MOVIES.DIRECTOR
WHERE DIRECTORS.YEAROFBIRTH < (
		EXTRACT(
			YEAR
			FROM CURRENT_DATE
		) - 50
	)
GROUP BY DIRECTORS.DIRECTOR
ORDER BY 1, 2, 3, 4 ASC;
