--v1.1
WITH T AS (
	SELECT MOVIEAWARDS.TITLE AS NAME,
		MOVIES.YEAR AS YEAR,
		COUNT(MOVIEAWARDS.AWARD)
	FROM MOVIEAWARDS
		LEFT JOIN MOVIES ON MOVIEAWARDS.TITLE = MOVIES.TITLE
	WHERE AWARD LIKE 'Oscar%'
		AND RESULT = 'won'
	GROUP BY MOVIEAWARDS.TITLE,
		MOVIES.YEAR
)
SELECT T.NAME,
	T.YEAR
FROM T
WHERE T.COUNT = (
		SELECT MAX(T.COUNT)
		FROM T
	)
ORDER BY 1,
	2 ASC;