--v1.0
WITH OSCARDIRECTORS AS (
    SELECT DIRECTORAWARDS.*,
        DIRECTORS.YEAROFBIRTH
    FROM DIRECTORAWARDS
        RIGHT JOIN DIRECTORS ON DIRECTORAWARDS.DIRECTOR = DIRECTORS.DIRECTOR
    WHERE AWARD LIKE 'oscar%'
        AND RESULT = 'won'
)
SELECT CASE
        WHEN OSCARDIRECTORS.YEAROFBIRTH = (
            SELECT MAX(OSCARDIRECTORS.YEAROFBIRTH)
            FROM OSCARDIRECTORS
        ) THEN 'youngest'
        ELSE 'oldest'
    END AS FEATURE,
    OSCARDIRECTORS.DIRECTOR
FROM OSCARDIRECTORS
WHERE (
        SELECT MAX(OSCARDIRECTORS.YEAROFBIRTH)
        FROM OSCARDIRECTORS
    ) = OSCARDIRECTORS.YEAROFBIRTH
    OR (
        SELECT MIN(OSCARDIRECTORS.YEAROFBIRTH)
        FROM OSCARDIRECTORS
    ) = OSCARDIRECTORS.YEAROFBIRTH
ORDER BY 1,
    2 ASC;