--v1.1

SELECT DISTINCT DIRECTORAWARDS.AWARD,
	DIRECTORAWARDS.YEAR,
	DIRECTORAWARDS.DIRECTOR
FROM DIRECTORAWARDS
WHERE DIRECTORAWARDS.DIRECTOR IN (
		SELECT DISTINCT MOVIES.DIRECTOR
		FROM MOVIES
		WHERE MOVIES.YEAR > (
				EXTRACT(
					YEAR
					FROM CURRENT_DATE
				)
			) - 5
		GROUP BY MOVIES.DIRECTOR
		HAVING SUM(MOVIES.GROSS) > 1000000
	)
	AND DIRECTORAWARDS.RESULT = 'won'
ORDER BY DIRECTORAWARDS.AWARD,
	DIRECTORAWARDS.YEAR,
	DIRECTORAWARDS.DIRECTOR;