SELECT MOVIES.TITLE,
    MOVIES.GROSS - MOVIES.BUDGET AS GROSS,
    MOVIES.BUDGET,
    CASE
        WHEN MOVIES.BUDGET = (
            SELECT (MIN(MOVIES.BUDGET))::REAL
            FROM MOVIES
        ) THEN 'least expensive'
        ELSE 'most profitable'
    END AS FEATURE
FROM MOVIES
WHERE (
        SELECT MAX(MOVIES.GROSS - MOVIES.BUDGET)
        FROM MOVIES
    ) = MOVIES.GROSS - MOVIES.BUDGET
    OR (
        SELECT MIN(MOVIES.BUDGET)
        FROM MOVIES
    ) = MOVIES.BUDGET;